### ISSUE TITLE
Datalogger data missing from GWI

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/sensor-data-pipeline#204]
![image](https://github.com/user-attachments/assets/f1cd28a4-4274-4d4b-ba2f-46367cfe69c5)

**Comment by bpbond** [comment]
I just checked the `COMPASS_PNNL_Rawdata_Archive` on Dropbox and none of the GWI dataloggers are writing `CheckTable` outputs, even though this happens at every other site.

@roylrich Is this intentional?

**Comment by roylrich** [comment]
This is becasue they are running an old version of code. I was on GWI yesterday and updated code for wetland site  to version 3.3 but need to allocate table to correct directory still. I asked SW if the solar check modules were in place becasue the data from that looked odd after code change. We are having issue at GWI-W where AQ600 is not showing up in table but I can manually connect to sensor via code. This is something that I have not seen before and maybe a campbell issue.  I can schedule my people to systematically push new code in next few weeks, this should coincide with code update that I need to do for SP and NW

**Comment by bpbond** [comment]
OK, thank you and thank you @stephpenn1 for identifying this! 

Roy, if possible let us know when the new tables are turned on? That we will know to check and ensure that the new GWI data are flowing through correctly.

**Comment by roylrich** [comment]
Ok, check table for GWI-W should be in place in next 45 minutes. The others will come on when we push new programs.-RR


Roy Rich PhD.

Research Ecologist



Smithsonian Environmental Research Center

647 Contees Wharf Rd.

Edgewater, MD USA 21037



Cell 651-328-4391

***@***.******@***.***>

https://serc.si.edu/technology-in-ecology



________________________________
