### ISSUE TITLE
Wrong depth assigned to TEROS sensor?

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/sensor-data-pipeline#209]
One of the plots I prepared for #208 is this one:

![Unknown](https://github.com/user-attachments/assets/857172cd-0db4-47ff-91a5-dac5bb6ace7e)

Look at the enormous jump that one (T173) of the 30cm lines takes -- hmm, do we think this is real? I wonder if it's actually at 5 or 15 cm.

**Comment by bpbond** [comment]
@aestearns01 See graph above...any concerns? I checked the "TEMPEST_TEROS_Network_Location&Status" spreadsheet and yes T173 is listed as 30 cm.

 
![vwc2](https://github.com/user-attachments/assets/15895535-ac01-4c60-acc8-ccc12e1270fa)

**Comment by bpbond** [comment]
Coming back to this, with apologies for the delay.

T173 is certainly spiking more strongly than any other 15 cm probe:

![teros](https://github.com/user-attachments/assets/fba4ece0-be06-4e74-9ab6-2f1ca0927238)

Here's the nest at Control H3:

![teros_nest](https://github.com/user-attachments/assets/f2dfc666-d141-4fb7-a394-3255f922add5)

Finally, here are all the multi-depth control plot nests in June 2021:
 
![teros_nest_control](https://github.com/user-attachments/assets/83b88ac5-e4ca-4da0-add9-5f5aefdb2519)

**Comment by bpbond** [comment]
I don't see anything conclusive here about a metadata mistake, and while T173 is jumpy, it's not wildly out of line with the others. So closing.

**Comment by aestearns01** [comment]
@bpbond Evan was able to verify in the field that T173 is indeed at 30 cm

**Comment by bpbond** [comment]
Thanks for the follow-up @aestearns01 🎉
